swagger: '2.0'
info:
  version: 1.0.0
  title: CountryByCurency
basePath: /api
schemes:
- "http"
host: 'localhost:3000'
consumes:
  - application/json
produces:
  - application/json
paths:
  /currencies/byCurrencyCode/{currencyCode}:
    get:
      tags:
        - Countries
      summary: Get List of Countries For a Currency Code.
      parameters:
        - name: currencyCode
          in: path
          description: 'Currency Code'
          required: true
          type: string
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: "#/definitions/Currency"
      deprecated: false
definitions:
  Currency:
    type: "array"
    items:
          type: "object"
    properties:
      CountryName:
        type: "string"
      CountryCode:
        type: "string"
      CountryCapital:
        type: "string"
      CurrenciesAccepted:
        type: "array"
        items:
              type: "object"
              properties:
                code:
                  type: "string"
                name:
                  type: "string"
                symbol:
                  type: "string"
